dev:
  Name: blog-api
  Host: 0.0.0.0
  Port: 8080

  Mysql:
    Host: 127.0.0.1 
    Port: 3306
    Username: root
    Password: zhangphh=520
    DatabaseName: blog
  
  Redis:
    Host: 127.0.0.1
    Port: 6379
    Password: ""
    DB: 1
    PoolSize: 50
    MinIdleConns: 10
    MaxRetries: 3