// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResponse struct {
	Id            int64  `json:"id"`
	Avatar        string `json:"avatar"`
	Email         string `json:"email"`
	Intro         string `json:"intro"`
	IpAddress     string `json:"ipAddress"`
	IpSource      string `json:"ipSource"`
	IsSubscribe   int8   `json:"isSubscribe"`
	LastLoginTime string `json:"lastLoginTime"`
	LoginType     int8   `json:"loginType"`
	Nickname      string `json:"nickname"`
	Token         string `json:"token"`
	Username      string `json:"username"`
	Website       string `json:"website"`
}
