// Code generated by goctl. DO NOT EDIT.
package types

type GetPhotoAlbumsRequest struct {
}

type GetPhotoAlbumsResponse struct {
	Id         int64  `json:"id"`
	AblumCover string `json:"ablumCover"`
	AlbumDesc  string `json:"albumDesc"`
	AlbumName  string `json:"albumName"`
}

type ApiResponse struct {
	ArticleCount  int64         `json:"articleCount"`
	CategoryCount int64         `json:"categoryCount"`
	TagCount      int64         `json:"tagCount"`
	TalkCount     int64         `json:"talkCount"`
	ViewCount     int64         `json:"viewCount"`
	WebSiteConfig WebSiteConfig `json:"webSiteConfig"`
}

type WebSiteConfig struct {
	Name              string `json:"name"`
	EnglishName       string `json:"englishName"`
	Author            string `json:"author"`
	AuthorAvatar      string `json:"authorAvatar"`
	AuthorIntro       string `json:"authorIntro"`
	Logo              string `json:"logo"`
	MultiLanguages    int64  `json:"multiLanguages"`
	Notice            string `json:"notice"`
	WebsiteCreateTime string `json:"websiteCreateTime"`
	BeianNumber       string `json:"beianNumber"`
	QQLogin           int64  `json:"qqLogin"`
	GitHub            string `json:"github"`
	QQ                string `json:"qq"`
	Gitee             string `json:"gitee"`
	WeChat            string `json:"weChat"`
	WeiBo             string `json:"weibo"`
	Csdn              string `json:"csdn"`
	Zhihu             string `json:"zhihu"`
	JueJin            string `json:"juejin"`
	Twitter           string `json:"twitter"`
	Stackoverflow     string `json:"stackoverflow"`
	TouristAvatar     string `json:"touristAvatar"`
	UserAvatar        string `json:"userAvatar"`
	IsCommentReview   int64  `json:"isCommentReview"`
	IsEmailNotice     int64  `json:"isEmailNotice"`
	IsReward          int64  `json:"isReward"`
	WeiXinQRCode      string `json:"weiXinQrCode"`
	AlipayQRCode      string `json:"alipayQrCode"`
}

type ReportResponse struct {
}
